&params
  ltt%lat_file = 'lat.bmad'
  ltt%ramping_on = T
  ltt%ramping_start_time = 0
  ltt%ele_start = ''
  ltt%ele_stop = ''

  ltt%phase_space_output_file = 'beam_notlost_dm_chi002'
  ltt%averages_output_file = 'out_dm_chi002'
  ltt%averages_output_every_n_turns = 1000
  ltt%beam_output_every_n_turns = 10000
  ltt%beam_output_file = 'beam_dm_chi002.out'
  ltt%particle_output_every_n_turns = 10000

  ltt%simulation_mode = 'BEAM'
  ltt%tracking_method = 'BMAD'
  ltt%n_turns = 100000
  ltt%rfcavity_on = T
  ltt%map_order = 3
  ltt%split_bends_for_stochastic_rad = F
  ltt%random_seed = 3972547
  ltt%timer_print_dtime = 300
  ltt%add_closed_orbit_to_init_position = T
  ltt%ptc_aperture = 0.012, 0.012

  bmad_com%spin_tracking_on = T
  bmad_com%radiation_damping_on = T
  bmad_com%radiation_fluctuations_on = T
  bmad_com%aperture_limit_on = T
  bmad_com%max_aperture_limit = 0.0178

  beam_init%n_particle = 2214
  beam_init%spin = 0.6, 0.0, 0.8
  beam_init%center = 0.0, 0.0, 0.0, 0.0, 0.0, 0.0
  beam_init%a_emit = 7.1e-10
  beam_init%b_emit = 2.3e-12
  beam_init%sig_z = 5.5e-3
  beam_init%sig_pz = 3.9e-4
/
